version: "3.8"

services:
  database:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "54322:5432"
volumes:
  db-data:
